name: build python module

on:
  workflow_dispatch:
  push:
    branches:
      - "modularize"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
                
    - name: Install dependencies and etc
      run: |
        python -m pip install --upgrade pip setuptools wheel     
        python -m pip install --upgrade pip
        make 
